"use client";
import Link from "next/link";
import { usePathname, useRouter } from "next/navigation";
import { useState } from "react";
import { authClient } from "@/lib/auth-client";
import { isolateGuestCart } from "@/features/cart/store/cart-store";

const nav=[["/admin","Overview","Â¦"],["/admin/orders","Orders","Â¤"],["/admin/products","Products","Ë‡"],["/admin/categories","Categories","Ã‡"],["/admin/inventory","Inventory","Ä„"],["/admin/customers","Customers","Y"],["/admin/staff","Staff","_"],["/admin/coupons","Coupons",""],["/admin/reports","Reports",""],["/admin/settings","Settings","â„¢"]];
export function AdminShell({children,user,unread}:{children:React.ReactNode;user:{name:string;email:string;role:string};unread:number|null}){
 const path=usePathname(),router=useRouter();const[open,setOpen]=useState(false);const[profile,setProfile]=useState(false);
 async function logout(){isolateGuestCart();await authClient.signOut();router.replace("/login");router.refresh()}
 const side=<><Link href="/admin" className="flex h-16 items-center gap-3 border-b border-white/10 px-5 text-lg font-bold"><span className="grid h-9 w-9 place-items-center rounded-xl bg-blue-500">W</span>worklab</Link><nav className="flex-1 space-y-1 overflow-y-auto p-3">{nav.map(([href,label,icon])=>{const active=href==="/admin"?path===href:path.startsWith(href);return <Link key={href} href={href} onClick={()=>setOpen(false)} className={"flex items-center gap-3 rounded-xl px-3 py-2.5 text-sm font-medium transition "+(active?"bg-blue-600 text-white shadow-lg shadow-blue-950/30":"text-slate-300 hover:bg-white/10 hover:text-white")}><span className="w-5 text-center">{icon}</span>{label}</Link>})}</nav><div className="border-t border-white/10 p-3"><button onClick={logout} className="w-full rounded-xl px-3 py-2.5 text-left text-sm text-slate-300 hover:bg-white/10">Åž Sign out</button></div></>;
 return <div className="min-h-screen bg-slate-50 text-slate-950"><aside className="fixed inset-y-0 left-0n-40 hidden w-64 flex-col bg-slate-950 text-white lg:flex">{side}</aside>{open&&<div className="fixed inset-0 z-50 lg:hidden"><button aria-label="Close menu" className="absolute inset-0 bg-slate-950/50" onClick={()=>setOpen(false)}/><aside className="relative flex h-full w-72 flex-col bg-slate-950 text-white">{side}</aside></div>}<div className="lg:pl-64"><header className="sticky top-0 z-30 flex h-16 items-center gap-3 border-b border-slate-200 bg-white/95 px-4 backdrop-blur sm:px-6"><button onClick={()=>setOpen(true)} className="grid h-10 w-10 place-items-center rounded-xl border lg:hidden" aria-label="Open menu">0</button><label className="relative hidden max-w-md flex-1 md:block"><span className="sr-only">Global search</span><input placeholder="Search orders, products, customers&" className="h-10 w-full rounded-xl border border-slate-200 bg-slate-50 px-4 text-sm outline-none focus:border-blue-500"/></label><div className="ml-auto flex items-center gap-2">{unread!==null&&<Link href="/admin/notifications" className="relative grid h-10 w-10 place-items-center rounded-xl border border-slate-200" aria-label={"Notifications"+(unread?` (${unread} unread)`:"")}><svg viewBox="0 0 24 24" aria-hidden="true" className="h-5 w-5" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round"><path d="M6 8a6 6 0 0 1 12 0c0 7 3 9 3 9H3s3-2 3-9M10.3 21a1.9 1.9 0 0 0 3.4 0"/></svg>{unread>0&&<span className="absolute -right-1.5 -top-1.5 grid h-5 min-w-5 place-items-center rounded-full bg-red-500 px-1 text-[10px] font-bold text-white">{unread>99?"99+":unread}</span>}</Link>}<div className="relative"><button onClick={()=>setProfile(!profile)} className="flex items-center gap-3 rounded-xl p-1.5 pr-3 hover:bg-slate-100"><span className="grid h-8 w-8 place-items-center rounded-lg bg-blue-100 font-bold text-blue-700">{user.name[0]?.toUpperCase()}</span><span className="hidden text-left sm:block"><b className="block text-xs">{user.name}</b><span className="block text-[10px] text-slate-500">{user.role.replaceAll("_"," ")}</span></span></button>{profile&&<div className="absolute right-0 mt-2 w-60 rounded-xl border bg-white p-3 shadow-xl"><p className="truncate text-sm font-semibold">{user.name}</p><p className="truncate text-xs text-slate-500">{user.email}</p><Link href="/admin/account" onClick={()=>setProfile(false)} className="mt-3 block rounded-lg p-2 text-sm hover:bg-slate-100">Change password</Link><button onClick={logout} className="mt-1 w-full rounded-lg bg-slate-100 p-2 text-left text-sm">Sign out</button></div>}</div></div></header><main className="p-4 sm:p-6 lg:p-8">{children}</main></div></div>
}
