import { SecuritySettings } from "@/features/account/components/security-settings";
import { formatDate } from "@/features/account/presentation";
import { listCustomerSecurity, requireCustomerPage } from "@/features/account/server/account.service";

export default async function SecurityPage() {
  const customer = await requireCustomerPage();
  const security = await listCustomerSecurity(customer.id);
  const connected = security.accounts.filter((account) => account.providerId !== "credential");
  return <section><p className="text-xs font-bold uppercase tracking-[0.16em] text-blue-700">Account protection</p><h2 className="mt-1 text-2xl font-black tracking-tight sm:text-3xl">Login & Security</h2><p className="mt-2 text-sm text-slate-500">Manage personal information and keep access to your account secure.</p><div className="mt-6"><SecuritySettings customer={customer} hasPassword={security.hasPassword}/></div><section className="mt-5 rounded-2xl border border-slate-200 bg-white p-5 shadow-sm sm:p-6"><h3 className="text-lg font-black">Connected accounts</h3>{connected.length?<ul className="mt-4 space-y-3">{connected.map(account=><li key={account.id} className="flex items-center justify-between rounded-xl bg-slate-50 p-4"><span className="font-bold capitalize">{account.providerId}</span><span className="text-xs text-slate-500">Connected {formatDate(account.createdAt)}</span></li>)}</ul>:<p className="mt-3 text-sm text-slate-500">No social accounts are connected.</p>}</section><section className="mt-5 rounded-2xl border border-slate-200 bg-white p-5 shadow-sm sm:p-6"><h3 className="text-lg font-black">Session history</h3><p className="mt-2 text-sm text-slate-500">{security.sessions.length} active sessions. Session tokens are never displayed.</p><ul className="mt-4 space-y-3">{security.sessions.slice(0,5).map(session=><li key={session.id} className="rounded-xl bg-slate-50 p-4 text-sm"><p className="font-bold">{session.userAgent?.split(" ").slice(0,4).join(" ") || "Unknown device"}</p><p className="mt-1 text-xs text-slate-500">Started {formatDate(session.createdAt,true)} · Expires {formatDate(session.expiresAt,true)}</p></li>)}</ul></section><section className="mt-5 rounded-2xl border border-red-200 bg-red-50 p-5 sm:p-6"><h3 className="font-black text-red-900">Delete account request</h3><p className="mt-2 text-sm text-red-800">Account deletion is reviewed so active orders and legal records remain protected.</p><a href="/account/support" className="mt-4 inline-flex min-h-11 items-center rounded-xl border border-red-300 bg-white px-4 text-sm font-bold text-red-800">Request account deletion</a></section></section>;
}
