import Link from "next/link";
import { db } from "@/lib/db";
import { requireAdminPage } from "@/lib/admin-auth";
const money=(v:bigint|number)=>new Intl.NumberFormat("en-IN",{style:"currency",currency:"INR",maximumFractionDigits:0}).format(Number(v)/100);
const label=(v:string)=>v.replaceAll("_"," ").toLowerCase().replace(/\b\w/g,c=>c.toUpperCase());
function startFor(range:string){const d=new Date();if(range==="today")d.setHours(0,0,0,0);else if(range==="7d")d.setDate(d.getDate()-6);else if(range==="30d")d.setDate(d.getDate()-29);else if(range==="month")d.setDate(1);else if(range==="year"){d.setMonth(0);d.setDate(1)}else d.setDate(d.getDate()-29);return d}
export default async function AdminDashboard({searchParams}:{searchParams:Promise<{range?:string;from?:string;to?:string}>}){
 await requireAdminPage();const q=await searchParams;const range=q.range??"30d";const from=q.from?new Date(q.from):startFor(range);const to=q.to?new Date(q.to):new Date();to.setHours(23,59,59,999);const where={createdAt:{gte:from,lte:to}};
 const [orders,revenue,customers,staff,recent,registrations,statuses,top]=await Promise.all([
  db.order.count({where}),db.order.aggregate({where:{...where,paymentStatus:"PAID"},_sum:{totalPaise:true}}),
  db.user.count({where:{role:"CUSTOMER"}}),db.user.count({where:{role:{not:"CUSTOMER"},accessEnabled:true}}),
  db.order.findMany({where,orderBy:{createdAt:"desc"},take:6,include:{sellerOrders:{include:{items:true}}}}),
  db.user.findMany({where:{role:"CUSTOMER"},orderBy:{createdAt:"desc"},take:5,select:{id:true,name:true,email:true,createdAt:true}}),
  db.order.groupBy({by:["status"],where,_count:{_all:true}}),
  db.orderItem.groupBy({by:["productName"],where:{createdAt:{gte:from,lte:to}},_sum:{quantity:true,totalPaise:true},orderBy:{_sum:{quantity:"desc"}},take:5})
 ]);
 const pending=statuses.filter(x=>!["DELIVERED","FULFILLED","CANCELLED","REFUNDED"].includes(x.status)).reduce((a,x)=>a+x._count._all,0);const cancelled=statuses.find(x=>x.status==="CANCELLED")?._count._all??0;
 const cards=[["Total revenue",money(revenue._sum.totalPaise??BigInt(0)),"‘"],["Total orders",orders,"¤"],["Total customers",customers,"Y"],["Total products","Catalog","ˇ"],["Staff count",staff,"_"],["Pending orders",pending,"÷"],["Cancelled orders",cancelled,"×"],["Low-stock products","Review","!"]];
 const max=Math.max(1,...statuses.map(x=>x._count._all));
 return <div className="mx-auto max-w-[1600px] space-y-6"><div className="flex flex-col gap-4 xl:flex-row xl:items-end xl:justify-between"><div><p className="text-sm font-semibold text-blue-600">Commerce control center</p><h1 className="mt-1 text-3xl font-bold tracking-tight">Dashboard overview</h1><p className="mt-1 text-sm text-slate-500">Live operational and sales performance.</p></div><form className="flex flex-wrap gap-2">{[["today","Today"],["7d","Last 7 days"],["30d","Last 30 days"],["month","Current month"],["year","Current year"]].map(([v,l])=><button key={v} name="range" value={v} className={"rounded-lg border px-3 py-2 text-xs font-semibold "+(range===v?"border-blue-600 bg-blue-600 text-white":"bg-white text-slate-600")}>{l}</button>)}<input type="date" name="from" defaultValue={q.from} className="rounded-lg border px-2 text-xs"/><input type="date" name="to" defaultValue={q.to} className="rounded-lg border px-2 text-xs"/><button className="rounded-lg bg-slate-900 px-3 text-xs text-white">Apply</button></form></div>
 <section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{cards.map(([title,value,icon])=><div key={title} className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex items-start justify-between"><div><p className="text-xs font-semibold uppercase tracking-wide text-slate-500">{title}</p><p className="mt-2 text-2xl font-bold">{value}</p></div><span className="grid h-10 w-10 place-items-center rounded-xl bg-blue-50 text-blue-700">{icon}</span></div></div>)}</section>
 <section className="grid gap-5 xl:grid-cols-[1.7fr_1fr]"><div className="rounded-2xl border bg-white p-5"><div className="flex justify-between"><div><h2 className="font-bold">Revenue & sales</h2><p className="text-xs text-slate-500">Orders by current status</p></div></div><div className="mt-8 flex h-52 items-end gap-3">{statuses.length?statuses.map(x=><div key={x.status} className="flex min-w-0 flex-1 flex-col items-center gap-2"><span className="text-xs font-bold">{x._count._all}</span><div className="w-full rounded-t-lg bg-gradient-to-t from-blue-700 to-cyan-400" style={{height:`${Math.max(12,x._count._all/max*160)}px`}}/><span className="w-full truncate text-center text-[10px] text-slate-500">{label(x.status)}</span></div>):<div className="m-auto text-sm text-slate-400">No sales in this period</div>}</div></div><div className="rounded-2xl border bg-white p-5"><h2 className="font-bold">Order status</h2><div className="mt-5 space-y-4">{statuses.map(x=><div key={x.status}><div className="mb-1 flex justify-between text-xs"><span>{label(x.status)}</span><b>{x._count._all}</b></div><div className="h-2 overflow-hidden rounded-full bg-slate-100"><div className="h-full rounded-full bg-blue-600" style={{width:`${x._count._all/max*100}%`}}/></div></div>)}{!statuses.length&&<p className="py-16 text-center text-sm text-slate-400">No order data</p>}</div></div></section>
 <section className="grid gap-5 xl:grid-cols-2"><div className="overflow-hidden rounded-2xl border bg-white"><div className="flex items-center justify-between p-5"><h2 className="font-bold">Recent orders</h2><Link href="/admin/orders" className="text-xs font-semibold text-blue-600">View all ’</Link></div><div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead className="bg-slate-50 text-xs text-slate-500"><tr><th className="p-3">Order</th><th>Customer</th><th>Status</th><th>Total</th></tr></thead><tbody>{recent.map(o=>{const buyer=o.buyerSnapshot as {name?:string;email?:string};return <tr key={o.id} className="border-t"><td className="p-3"><Link href={`/admin/orders/${o.id}`} className="font-semibold text-blue-700">{o.orderNumber}</Link></td><td>{buyer.name??buyer.email??"Guest"}</td><td><span className="rounded-full bg-slate-100 px-2 py-1 text-[10px] font-bold">{label(o.status)}</span></td><td>{money(o.totalPaise)}</td></tr>})}</tbody></table>{!recent.length&&<p className="p-10 text-center text-sm text-slate-400">No recent orders</p>}</div></div><div className="rounded-2xl border bg-white p-5"><h2 className="font-bold">Top-selling products</h2><div className="mt-4 divide-y">{top.map((p,i)=><div key={p.productName} className="flex items-center gap-3 py-3"><span className="grid h-8 w-8 place-items-center rounded-lg bg-slate-100 text-xs font-bold">{i+1}</span><div className="min-w-0 flex-1"><p className="truncate text-sm font-semibold">{p.productName}</p><p className="text-xs text-slate-500">{p._sum.quantity??0} units sold</p></div><b className="text-sm">{money(p._sum.totalPaise??BigInt(0))}</b></div>)}{!top.length&&<p className="py-10 text-center text-sm text-slate-400">No product sales yet</p>}</div></div></section>
 <section className="rounded-2xl border bg-white p-5"><h2 className="font-bold">Recent customer registrations</h2><div className="mt-4 grid gap-3 md:grid-cols-2 xl:grid-cols-5">{registrations.map(u=><div key={u.id} className="rounded-xl bg-slate-50 p-3"><p className="truncate text-sm font-semibold">{u.name}</p><p className="truncate text-xs text-slate-500">{u.email}</p><p className="mt-2 text-[10px] text-slate-400">{u.createdAt.toLocaleDateString("en-IN")}</p></div>)}{!registrations.length&&<p className="text-sm text-slate-400">No customers yet</p>}</div></section></div>
}
